# Generated by Django 2.1.7 on 2019-04-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190402_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
    ]
