# Generated by Django 2.1.7 on 2019-04-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='course',
            name='review',
        ),
    ]
