# Generated by Django 2.1.7 on 2019-04-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190413_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gen_ed',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
