# Generated by Django 2.1.7 on 2019-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
